repos:

    - repo: https://github.com/humitos/mirrors-autoflake
      rev: v1.1
      hooks:
        - id: autoflake
          args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.9.3
      hooks:
      - id: isort
        additional_dependencies:
        - toml

    - repo: https://github.com/ambv/black
      rev: 21.11b1
      hooks:
      - id: black
        language_version: python3.6

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-yaml
      - id: check-toml

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
      - id: flake8
