[tool.poetry]
name = "lirc"
version = "0.0.0"
description = "Interact with the daemon in the Linux Infrared Remote Control package"
authors = ["Eugene Triguba <eugenetriguba@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Bumblebee-Tester/lirc"
keywords = [
    "LIRC",
    "IR",
    "linux"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.6",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.taskipy.tasks]
lint = "pre-commit run --all"
test = "poetry run task test_unit"
test_unit = "poetry run pytest -v --cov=lirc/ --cov-report term-missing tests/"
test_all = "export LIRC_RUN_LONG_TESTS=true && poetry run task test && unset LIRC_RUN_LONG_TESTS"


[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pre-commit = { version = "^2.6.0", python = "^3.6.1" }
flake8 = "^3.8.3"
isort = "^5.0.4"
seed-isort-config = { version = "^2.2.0", python = "^3.6.1" }
pytest = "^5.4.3"
pytest-cov = "^2.10.0"
pytest-sugar = "^0.9.4"
bump2version = "^1.0.0"
taskipy = "^1.2.1"
black = "^19.10b0"

[tool.black]
line-length = 88
target_version = ['py38']
include = '\.pyi?$'

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_first_party = ["lirc"]
known_third_party = ["pytest"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
