name: Test

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        versions:
          [
            { python: "3.9", poetry: "1.8.4" },
            { python: "3.10", poetry: "1.8.4" },
            { python: "3.11", poetry: "1.8.4" },
            { python: "3.12", poetry: "1.8.4" },
            { python: "3.13", poetry: "1.8.4" },
          ]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Poetry
        run: pipx install poetry==${{ matrix.versions.poetry }}

      - name: Set up Python ${{ matrix.versions.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.versions.python }}
          cache: "poetry"

      - name: Install Dependencies
        run: poetry install -v

      - name: Install system LIRC
        run: sudo apt-get install lirc

      - name: Run tests
        run: poetry run task test_ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Build Package
        run: poetry build
